#!/usr/bin/env python3

from src.main import *
from lib.misc import Banner

print(Banner.name_logo)
if __name__ == '__main__':
	try:
		Occli(args)
			
	except KeyboardInterrupt:
	    print(f'{Attributes.warning} Process interrupted with (Ctrl+C).')
				
	except IndexError:
	    pass
		    
	except Exception as e:
	    print(f'{Attributes.error} An error occured: {e}')
		    
print(f'{Attributes.info} Finished in {datetime.now()-start_time} seconds.')
